import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, DatabaseBackup, ExternalLink, ShieldCheck } from "lucide-react";

export function DatabaseMaintenancePage() {
  const access = trpc.municipal.databaseMaintenance.access.useQuery();
  if (access.isLoading) return <div className="p-6 text-sm text-slate-600">Vérification de l’habilitation de maintenance…</div>;
  if (access.error) return <div className="m-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-900"><strong>Accès refusé.</strong> {access.error.message}</div>;
  return <div className="space-y-6">
    <section className="rounded-3xl border border-slate-700 bg-gradient-to-r from-slate-950 via-slate-800 to-blue-950 p-6 text-white shadow-[0_18px_45px_rgba(15,23,42,.26)]"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-200">Responsables habilités uniquement</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Base de données</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-200">Espace de maintenance protégé par le droit <code className="rounded bg-white/10 px-1.5 py-0.5">{access.data?.permissionCode}</code>. Toute maintenance doit être préparée, tracée et vérifiée avant remise en service.</p></section>
    <Card className="border-amber-300 bg-amber-50"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-950"><AlertTriangle className="size-5" />Sauvegarde et restauration de la plateforme gérée</CardTitle><CardDescription className="text-amber-900">Le mécanisme de sauvegarde de la plateforme préserve ensemble les données, fichiers, configuration et secrets. Un export SQL isolé ou une importation SQL exécutée depuis l’application risquerait de rompre les contraintes, les migrations et les sessions de sécurité.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3"><Button asChild className="bg-blue-700 hover:bg-blue-800"><a href={access.data?.backupUrl} target="_blank" rel="noreferrer"><DatabaseBackup className="mr-2 size-4" />Ouvrir la sauvegarde sécurisée<ExternalLink className="ml-2 size-3.5" /></a></Button><span className="self-center text-sm text-amber-950">Créez un instantané avant toute opération de maintenance.</span></CardContent></Card>
    <div className="grid gap-5 lg:grid-cols-2"><Card className="border-blue-200"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5 text-blue-700" />Procédure de restauration</CardTitle><CardDescription>Utilisez exclusivement une sauvegarde complète et récente correspondant à cette plateforme.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm leading-6 text-slate-700"><ol className="list-decimal space-y-2 pl-5"><li>Mettre fin aux opérations de saisie et consigner la période concernée.</li><li>Créer et vérifier un nouvel instantané complet.</li><li>Restaurer l’instantané au moyen de l’outil sécurisé de la plateforme.</li><li>Contrôler les comptes, obligations, encaissements et journal d’audit avant reprise.</li></ol></CardContent></Card><Card className="border-slate-200"><CardHeader><CardTitle>Purge opérationnelle</CardTitle><CardDescription>Une purge irréversible exige de préciser son périmètre métier : données opérationnelles seulement ou aussi référentiels, utilisateurs et paramétrages.</CardDescription></CardHeader><CardContent className="text-sm leading-6 text-slate-700">Le journal d’audit est explicitement exclu de toute purge. La commande reste volontairement indisponible tant que ce périmètre et le circuit de double validation ne sont pas confirmés par la mairie.</CardContent></Card></div>
  </div>;
}
