import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { trpc } from "@/lib/trpc";
import { Calculator, FilePlus2, Link2, SlidersHorizontal } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { previewTaxAmount } from "@shared/taxCalculation";

type ErrorLike = { message: string };
const today = () => new Date().toISOString().slice(0, 10);
const euro = new Intl.NumberFormat("fr-FR", { style: "decimal", maximumFractionDigits: 0 });
const selectStyle = "mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-900";

function TaxEstimatePreview() {
  const [baseAmount, setBaseAmount] = useState(1000);
  const [exemptionPercent, setExemptionPercent] = useState(0);
  const [penaltyPercent, setPenaltyPercent] = useState(0);
  const [daysLate, setDaysLate] = useState(0);
  const estimate = previewTaxAmount({ baseAmount, exemptionRate: exemptionPercent / 100, penaltyRate: penaltyPercent / 100, daysLate });

  return <Card className="border-blue-200 bg-blue-50"><CardHeader className="pb-3"><div className="flex items-center gap-2"><Calculator className="size-5 text-blue-700" /><CardTitle className="text-base">Prévisualiser le calcul</CardTitle></div><CardDescription>Vérifiez le montant avant de créer ou d’affecter une règle. Cette estimation ne crée aucune obligation.</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><div><Label>Montant de base (XAF)</Label><Input type="number" min="0" value={baseAmount} onChange={event => setBaseAmount(Number(event.target.value) || 0)} className="mt-1" /></div><div><Label>Exonération (%)</Label><Input type="number" min="0" max="100" value={exemptionPercent} onChange={event => setExemptionPercent(Number(event.target.value) || 0)} className="mt-1" /></div><div><Label>Pénalité (%)</Label><Input type="number" min="0" max="100" value={penaltyPercent} onChange={event => setPenaltyPercent(Number(event.target.value) || 0)} className="mt-1" /></div><div><Label>Jours de retard</Label><Input type="number" min="0" value={daysLate} onChange={event => setDaysLate(Number(event.target.value) || 0)} className="mt-1" /></div></div><div className="mt-4 grid gap-2 rounded-xl border border-blue-200 bg-white p-3 text-sm md:grid-cols-4"><p>Base : <strong>{euro.format(estimate.baseAmount)} XAF</strong></p><p>Exonération : <strong>- {euro.format(estimate.exemptionAmount)} XAF</strong></p><p>Pénalité : <strong>+ {euro.format(estimate.penaltyAmount)} XAF</strong></p><p className="text-blue-900">À percevoir : <strong>{euro.format(estimate.totalAmount)} XAF</strong></p></div></CardContent></Card>;
}

export function TaxationWorkspace() {
  const catalog = trpc.municipal.catalog.options.useQuery();
  const rules = trpc.municipal.taxation.rules.useQuery();
  const activities = trpc.municipal.activities.list.useQuery();
  const obligations = trpc.municipal.taxation.obligations.useQuery();
  const utils = trpc.useUtils();
  const refreshCatalog = () => { utils.municipal.catalog.options.invalidate(); utils.municipal.taxation.rules.invalidate(); };
  const createTaxCategory = trpc.municipal.catalog.createTaxCategory.useMutation({ onSuccess: () => { toast.success("Catégorie de taxe créée."); refreshCatalog(); }, onError: (error: ErrorLike) => toast.error(error.message) });
  const createTaxType = trpc.municipal.catalog.createTaxType.useMutation({ onSuccess: () => { toast.success("Type de taxe créé."); refreshCatalog(); }, onError: (error: ErrorLike) => toast.error(error.message) });
  const createPeriodicity = trpc.municipal.catalog.createPeriodicity.useMutation({ onSuccess: () => { toast.success("Périodicité créée."); refreshCatalog(); }, onError: (error: ErrorLike) => toast.error(error.message) });
  const createRule = trpc.municipal.taxation.createRule.useMutation({ onSuccess: () => { toast.success("Règle fiscale créée. Affectez-la maintenant à une activité."); refreshCatalog(); }, onError: (error: ErrorLike) => toast.error(error.message) });
  const assignRule = trpc.municipal.taxation.assignRuleToActivity.useMutation({ onSuccess: () => { toast.success("Règle fiscale affectée à l’activité."); }, onError: (error: ErrorLike) => toast.error(error.message) });
  const generate = trpc.municipal.taxation.generateForActivity.useMutation({ onSuccess: result => { toast.success(result.createdCount ? `${result.createdCount} obligation(s) générée(s).` : "Aucune nouvelle obligation : la période est déjà générée ou aucune règle n’est affectée."); utils.municipal.taxation.obligations.invalidate(); }, onError: (error: ErrorLike) => toast.error(error.message) });

  return <div className="space-y-6"><section className="rounded-2xl border border-blue-200 bg-gradient-to-r from-blue-800 to-blue-600 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-100">Paramétrage fiscal</p><h1 className="mt-2 text-3xl font-bold">Fiscalité et obligations</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-blue-50">Le cycle suit quatre étapes : définir la taxe et sa périodicité, créer la règle tarifaire, l’affecter à une activité, puis générer les obligations de la période. Une obligation ne naît pas automatiquement sans règle affectée.</p></section>
    <TaxEstimatePreview />
    <div className="grid gap-5 xl:grid-cols-3"><Card className="border-blue-100"><CardHeader><Badge className="w-fit bg-blue-700">Étape 1</Badge><CardTitle className="mt-3">Référentiels fiscaux</CardTitle><CardDescription>Créez les éléments qui seront sélectionnés dans la règle tarifaire.</CardDescription></CardHeader><CardContent className="space-y-4"><form className="space-y-2 rounded-xl bg-slate-50 p-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); createTaxCategory.mutate({ code: String(data.get("code")), label: String(data.get("label")) }); event.currentTarget.reset(); }}><p className="text-sm font-semibold">Catégorie de taxe</p><Input name="code" placeholder="Ex. MARCHE" required /><Input name="label" placeholder="Ex. Taxes de marché" required /><Button type="submit" size="sm" className="w-full bg-blue-700 hover:bg-blue-800">Ajouter</Button></form><form className="space-y-2 rounded-xl bg-slate-50 p-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); createTaxType.mutate({ categoryId: String(data.get("categoryId")) || undefined, code: String(data.get("code")), label: String(data.get("label")) }); event.currentTarget.reset(); }}><p className="text-sm font-semibold">Type de taxe</p><select name="categoryId" className={selectStyle}><option value="">Sans catégorie</option>{catalog.data?.taxCategories.map(category => <option key={category.id} value={category.id}>{category.label}</option>)}</select><Input name="code" placeholder="Ex. DROIT_PLACE" required /><Input name="label" placeholder="Ex. Droit de place" required /><Button type="submit" size="sm" variant="outline" className="w-full">Ajouter</Button></form><form className="space-y-2 rounded-xl bg-slate-50 p-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); createPeriodicity.mutate({ code: String(data.get("code")), label: String(data.get("label")), calendarUnit: String(data.get("unit")) as "DAY" | "WEEK" | "MONTH" | "QUARTER" | "SEMESTER" | "YEAR" | "CUSTOM", intervalCount: 1 }); event.currentTarget.reset(); }}><p className="text-sm font-semibold">Périodicité</p><Input name="code" placeholder="Ex. JOURNALIER" required /><Input name="label" placeholder="Ex. Tous les jours" required /><select name="unit" className={selectStyle}><option value="DAY">Jour</option><option value="WEEK">Semaine</option><option value="MONTH">Mois</option><option value="YEAR">Année</option></select><Button type="submit" size="sm" variant="outline" className="w-full">Ajouter</Button></form></CardContent></Card>
      <Card className="border-blue-100 xl:col-span-2"><CardHeader><Badge className="w-fit bg-blue-700">Étape 2</Badge><CardTitle className="mt-3">Créer une règle tarifaire</CardTitle><CardDescription>Le montant de base est affiché avant la génération. Vous pourrez ensuite associer cette règle à une ou plusieurs activités.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); createRule.mutate({ taxTypeId: String(data.get("taxTypeId")), periodicityId: String(data.get("periodicityId")), code: String(data.get("code")), label: String(data.get("label")), baseAmount: Number(data.get("baseAmount")), graceDays: Number(data.get("graceDays") || 0), penaltyRate: Number(data.get("penaltyRate") || 0) / 100, validFrom: new Date(String(data.get("validFrom"))) }); event.currentTarget.reset(); }}><div><Label>Type de taxe</Label><select name="taxTypeId" className={selectStyle} required><option value="">Sélectionner</option>{catalog.data?.taxTypes.map(type => <option key={type.id} value={type.id}>{type.label}</option>)}</select></div><div><Label>Périodicité</Label><select name="periodicityId" className={selectStyle} required><option value="">Sélectionner</option>{catalog.data?.periodicities.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div><div><Label>Code</Label><Input name="code" placeholder="Ex. PLACE_JOUR" required className="mt-1" /></div><div><Label>Libellé de la règle</Label><Input name="label" placeholder="Ex. Droit de place journalier" required className="mt-1" /></div><div><Label>Montant de base (XAF)</Label><Input name="baseAmount" type="number" min="0" step="1" required className="mt-1" /></div><div><Label>Date d’effet</Label><Input name="validFrom" type="date" defaultValue={today()} required className="mt-1" /></div><div><Label>Jours de grâce</Label><Input name="graceDays" type="number" min="0" defaultValue="0" className="mt-1" /></div><div><Label>Pénalité (%)</Label><Input name="penaltyRate" type="number" min="0" max="100" defaultValue="0" className="mt-1" /></div><div className="md:col-span-2"><Button type="submit" disabled={createRule.isPending} className="bg-blue-700 hover:bg-blue-800"><SlidersHorizontal className="mr-2 size-4" />Créer la règle fiscale</Button></div></form></CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card className="border-blue-100"><CardHeader><Badge className="w-fit bg-blue-700">Étape 3</Badge><CardTitle className="mt-3">Affecter la règle à l’activité</CardTitle><CardDescription>L’affectation est indispensable : elle détermine quelle taxe l’activité doit produire.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-[1fr,1fr,auto] md:items-end" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); assignRule.mutate({ activityId: String(data.get("activityId")), taxRuleId: String(data.get("taxRuleId")), startDate: new Date(String(data.get("startDate"))) }); }}><div><Label>Activité</Label><select name="activityId" className={selectStyle} required><option value="">Sélectionner</option>{activities.data?.map(({ activity }) => <option key={activity.id} value={activity.id}>{activity.reference} · {activity.label}</option>)}</select></div><div><Label>Règle fiscale</Label><select name="taxRuleId" className={selectStyle} required><option value="">Sélectionner</option>{rules.data?.filter(({ rule }) => rule.isActive).map(({ rule, taxType }) => <option key={rule.id} value={rule.id}>{rule.label} · {euro.format(Number(rule.baseAmount))} XAF · {taxType.label}</option>)}</select></div><div><Label>Début</Label><Input name="startDate" type="date" defaultValue={today()} className="mt-1" required /><Button type="submit" disabled={assignRule.isPending} className="mt-2 w-full bg-blue-700 hover:bg-blue-800"><Link2 className="mr-2 size-4" />Affecter</Button></div></form></CardContent></Card>
      <Card className="border-blue-100"><CardHeader><Badge className="w-fit bg-blue-700">Étape 4</Badge><CardTitle className="mt-3">Générer les obligations</CardTitle><CardDescription>Choisissez l’activité et la période. L’opération est idempotente : la même règle et la même période ne créent pas de doublon.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-[1fr,1fr,1fr]" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); generate.mutate({ activityId: String(data.get("activityId")), periodStart: new Date(String(data.get("periodStart"))), periodEnd: new Date(String(data.get("periodEnd"))), dueDate: new Date(String(data.get("dueDate"))) }); }}><div className="md:col-span-3"><Label>Activité à générer</Label><select name="activityId" className={selectStyle} required><option value="">Sélectionner</option>{activities.data?.map(({ activity }) => <option key={activity.id} value={activity.id}>{activity.reference} · {activity.label}</option>)}</select></div><div><Label>Début de période</Label><Input name="periodStart" type="date" defaultValue={today()} className="mt-1" required /></div><div><Label>Fin de période</Label><Input name="periodEnd" type="date" defaultValue={today()} className="mt-1" required /></div><div><Label>Échéance</Label><Input name="dueDate" type="date" defaultValue={today()} className="mt-1" required /></div><div className="md:col-span-3"><Button type="submit" disabled={generate.isPending} className="bg-blue-700 hover:bg-blue-800"><Calculator className="mr-2 size-4" />Générer les obligations</Button></div></form></CardContent></Card></div>
    <Card className="border-blue-100"><CardHeader><CardTitle>Règles et obligations enregistrées</CardTitle><CardDescription>Ce tableau permet de contrôler la chaîne complète avant d’ouvrir l’encaissement. Le montant initial reste affiché même lorsqu’une obligation est intégralement réglée.</CardDescription></CardHeader><CardContent><div className="grid gap-5 lg:grid-cols-2"><div><p className="mb-3 font-semibold text-slate-900">Règles fiscales</p><div className="space-y-2">{rules.data?.length ? rules.data.map(({ rule, taxType, periodicity }) => <div key={rule.id} className="rounded-xl border border-slate-200 p-3"><p className="font-medium text-slate-950">{rule.label}</p><p className="mt-1 text-sm text-slate-600">{taxType.label} · {periodicity.label} · <strong>{euro.format(Number(rule.baseAmount))} XAF</strong></p></div>) : <p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">Aucune règle créée.</p>}</div></div><div><p className="mb-3 font-semibold text-slate-900">Obligations générées</p><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Référence</TableHead><TableHead>Montant initial</TableHead><TableHead>Reste dû</TableHead><TableHead>État</TableHead></TableRow></TableHeader><TableBody>{obligations.data?.length ? obligations.data.map(({ obligation }) => <TableRow key={obligation.id}><TableCell className="font-mono text-xs text-blue-800">{obligation.reference}</TableCell><TableCell>{euro.format(Number(obligation.expectedAmount))} XAF</TableCell><TableCell>{euro.format(Number(obligation.remainingAmount))} XAF</TableCell><TableCell><Badge variant="outline">{obligation.status}</Badge></TableCell></TableRow>) : <TableRow><TableCell colSpan={4} className="py-8 text-center text-sm text-slate-500">Aucune obligation générée.</TableCell></TableRow>}</TableBody></Table></div></div></div></CardContent></Card></div>;
}
