import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { useOfflineCreate } from "@/hooks/useOfflineCreate";
import { Building2, MapPinned, Store, Warehouse } from "lucide-react";
import { FormEvent } from "react";
import { toast } from "sonner";

type ErrorLike = { message: string };

function HierarchyCard({ step, title, description, children }: { step: string; title: string; description: string; children: React.ReactNode }) {
  return <Card className="border-blue-100 shadow-sm"><CardHeader><Badge className="w-fit bg-blue-700">Étape {step}</Badge><CardTitle className="mt-3 text-lg text-slate-950">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card>;
}

export function TerritoryWorkspace() {
  const tree = trpc.municipal.territory.tree.useQuery();
  const offline = useOfflineCreate();
  const utils = trpc.useUtils();
  const refresh = (label: string) => () => { toast.success(`${label} ajouté à la hiérarchie.`); utils.municipal.territory.tree.invalidate(); };
  const createSector = trpc.municipal.territory.createSector.useMutation({ onSuccess: refresh("Secteur"), onError: (error: ErrorLike) => toast.error(error.message) });
  const createZone = trpc.municipal.territory.createZone.useMutation({ onSuccess: refresh("Zone"), onError: (error: ErrorLike) => toast.error(error.message) });
  const createMarket = trpc.municipal.territory.createMarket.useMutation({ onSuccess: refresh("Marché"), onError: (error: ErrorLike) => toast.error(error.message) });
  const createLocation = trpc.municipal.territory.createLocation.useMutation({ onSuccess: refresh("Emplacement"), onError: (error: ErrorLike) => toast.error(error.message) });
  const sectorsById = Object.fromEntries((tree.data?.sectors ?? []).map(item => [item.id, item]));
  const zonesById = Object.fromEntries((tree.data?.zones ?? []).map(item => [item.id, item]));
  const marketsById = Object.fromEntries((tree.data?.markets ?? []).map(item => [item.id, item]));
  const selectStyle = "mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-900";
  const localCreates = offline.queue.filter(item => item.entityType === "offline.create").map(item => ({ id: item.entityId, ...(item.payload as { command: string; payload: Record<string, unknown> }) }));
  const sectorOptions = [...(tree.data?.sectors ?? []), ...localCreates.filter(item => item.command === "SECTOR").map(item => ({ id: item.id, code: String(item.payload.code), name: String(item.payload.name) }))];
  const zoneOptions = [...(tree.data?.zones ?? []), ...localCreates.filter(item => item.command === "ZONE").map(item => ({ id: item.id, sectorId: String(item.payload.sectorId), code: String(item.payload.code), name: String(item.payload.name) }))];
  const marketOptions = [...(tree.data?.markets ?? []), ...localCreates.filter(item => item.command === "MARKET").map(item => ({ id: item.id, zoneId: String(item.payload.zoneId), code: String(item.payload.code), name: String(item.payload.name) }))];

  return <div className="space-y-6"><section className="rounded-2xl border border-blue-200 bg-gradient-to-r from-blue-800 to-blue-600 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-100">Référentiel géographique</p><h1 className="mt-2 text-3xl font-bold">Territoire municipal</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-blue-50">Construisez la hiérarchie dans l’ordre obligatoire : <strong>Mairie → Secteur → Zone → Marché → Emplacement</strong>. Un niveau enfant ne peut être créé sans son parent.</p></section>
    <div className="grid gap-5 xl:grid-cols-4"><HierarchyCard step="1" title="Secteur" description="Premier découpage opérationnel de la mairie."><form className="space-y-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const payload = { code: String(data.get("code")), name: String(data.get("name")) }; if (!offline.online) { offline.defer("SECTOR", payload, `Secteur ${payload.name}`); toast.success("Secteur enregistré localement."); } else createSector.mutate(payload); event.currentTarget.reset(); }}><Input name="code" placeholder="Code, ex. NORD" required /><Input name="name" placeholder="Nom du secteur" required /><Button type="submit" disabled={createSector.isPending} className="w-full bg-blue-700 hover:bg-blue-800">Ajouter le secteur</Button></form></HierarchyCard>
      <HierarchyCard step="2" title="Zone" description="Une zone dépend toujours d’un secteur."><form className="space-y-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const payload = { sectorId: String(data.get("sectorId")), code: String(data.get("code")), name: String(data.get("name")) }; if (!offline.online) { offline.defer("ZONE", payload, `Zone ${payload.name}`); toast.success("Zone enregistrée localement."); } else createZone.mutate(payload); event.currentTarget.reset(); }}><select name="sectorId" className={selectStyle} required><option value="">Secteur parent</option>{sectorOptions.map(item => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><Input name="code" placeholder="Code, ex. NORD-01" required /><Input name="name" placeholder="Nom de la zone" required /><Button type="submit" disabled={!sectorOptions.length || createZone.isPending} className="w-full bg-blue-700 hover:bg-blue-800">Ajouter la zone</Button></form></HierarchyCard>
      <HierarchyCard step="3" title="Marché" description="Un marché dépend toujours d’une zone."><form className="space-y-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const payload = { zoneId: String(data.get("zoneId")), code: String(data.get("code")), name: String(data.get("name")), address: String(data.get("address") || "") || undefined }; if (!offline.online) { offline.defer("MARKET", payload, `Marché ${payload.name}`); toast.success("Marché enregistré localement."); } else createMarket.mutate(payload); event.currentTarget.reset(); }}><select name="zoneId" className={selectStyle} required><option value="">Zone parente</option>{zoneOptions.map(item => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><Input name="code" placeholder="Code, ex. MAR-001" required /><Input name="name" placeholder="Nom du marché" required /><Input name="address" placeholder="Adresse (facultative)" /><Button type="submit" disabled={!zoneOptions.length || createMarket.isPending} className="w-full bg-blue-700 hover:bg-blue-800">Ajouter le marché</Button></form></HierarchyCard>
      <HierarchyCard step="4" title="Emplacement" description="Un emplacement dépend toujours d’un marché."><form className="space-y-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const payload = { marketId: String(data.get("marketId")), code: String(data.get("code")), label: String(data.get("label")) }; if (!offline.online) { offline.defer("MARKET_LOCATION", payload, `Emplacement ${payload.label}`); toast.success("Emplacement enregistré localement."); } else createLocation.mutate(payload); event.currentTarget.reset(); }}><select name="marketId" className={selectStyle} required><option value="">Marché parent</option>{marketOptions.map(item => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><Input name="code" placeholder="Code, ex. A-001" required /><Input name="label" placeholder="Libellé de l’emplacement" required /><Button type="submit" disabled={!marketOptions.length || createLocation.isPending} className="w-full bg-blue-700 hover:bg-blue-800">Ajouter l’emplacement</Button></form></HierarchyCard></div>
    <Card className="border-blue-100"><CardHeader><CardTitle className="text-slate-950">Arbre territorial en place</CardTitle><CardDescription>Chaque élément est affiché avec son parent pour vous permettre de contrôler la cohérence de la hiérarchie.</CardDescription></CardHeader><CardContent>{tree.isLoading ? <p className="text-sm text-slate-600">Chargement du territoire…</p> : <div className="grid gap-5 lg:grid-cols-2"><div className="space-y-3"><p className="flex items-center gap-2 font-semibold text-blue-900"><Building2 className="size-4" />Secteurs et zones</p>{tree.data?.sectors.map(sector => <div key={sector.id} className="rounded-xl border border-slate-200 p-4"><p className="font-medium text-slate-950">{sector.code} · {sector.name}</p><div className="mt-2 space-y-1">{tree.data?.zones.filter(zone => zone.sectorId === sector.id).map(zone => <p key={zone.id} className="text-sm text-slate-600">↳ {zone.code} · {zone.name}</p>)}{!tree.data?.zones.some(zone => zone.sectorId === sector.id) && <p className="text-sm text-slate-400">Aucune zone</p>}</div></div>)}</div><div className="space-y-3"><p className="flex items-center gap-2 font-semibold text-blue-900"><Store className="size-4" />Marchés et emplacements</p>{tree.data?.markets.map(market => { const zone = zonesById[market.zoneId]; const sector = zone ? sectorsById[zone.sectorId] : undefined; return <div key={market.id} className="rounded-xl border border-slate-200 p-4"><p className="font-medium text-slate-950">{market.code} · {market.name}</p><p className="mt-1 text-xs text-slate-500">{sector?.name ?? "Secteur inconnu"} → {zone?.name ?? "Zone inconnue"}</p><div className="mt-2 space-y-1">{tree.data?.locations.filter(location => location.marketId === market.id).map(location => <p key={location.id} className="flex items-center gap-2 text-sm text-slate-600"><Warehouse className="size-3" />{location.code} · {location.label}</p>)}{!tree.data?.locations.some(location => location.marketId === market.id) && <p className="text-sm text-slate-400">Aucun emplacement</p>}</div></div>})}</div></div>}</CardContent></Card>
  </div>;
}
